system_ss.add(when: 'CONFIG_HYPERV', if_true: files('hyperv.cpp'))
system_ss.add(when: 'CONFIG_HYPERV_TESTDEV', if_true: files('hyperv_testdev.cpp'))
system_ss.add(when: 'CONFIG_VMBUS', if_true: files('vmbus.cpp'))
system_ss.add(when: 'CONFIG_SYNDBG', if_true: files('syndbg.cpp'))
system_ss.add(when: 'CONFIG_HV_BALLOON', if_true: files('hv-balloon.cpp', 'hv-balloon-page_range_tree.cpp', 'hv-balloon-our_range_memslots.cpp'))
system_ss.add(when: 'CONFIG_HV_BALLOON', if_false: files('hv-balloon-stub.cpp'))
