ipmi_ss = ss.source_set()
ipmi_ss.add(when: 'CONFIG_IPMI', if_true: files('ipmi.cpp', 'ipmi_kcs.cpp', 'ipmi_bt.cpp'))
ipmi_ss.add(when: 'CONFIG_IPMI_LOCAL', if_true: files('ipmi_bmc_sim.cpp'))
ipmi_ss.add(when: 'CONFIG_IPMI_EXTERN', if_true: files('ipmi_bmc_extern.cpp'))
ipmi_ss.add(when: 'CONFIG_ISA_IPMI_KCS', if_true: files('isa_ipmi_kcs.cpp'))
ipmi_ss.add(when: 'CONFIG_PCI_IPMI_KCS', if_true: files('pci_ipmi_kcs.cpp'))
ipmi_ss.add(when: 'CONFIG_ISA_IPMI_BT', if_true: files('isa_ipmi_bt.cpp'))
ipmi_ss.add(when: 'CONFIG_PCI_IPMI_BT', if_true: files('pci_ipmi_bt.cpp'))
ipmi_ss.add(when: 'CONFIG_IPMI_SSIF', if_true: files('smbus_ipmi.cpp'))

system_ss.add_all(when: 'CONFIG_IPMI', if_true: ipmi_ss)
